### ISSUE TITLE
Error building maven java project

### ISSUE THREAD

**Issue by danielf80** [dnp3/opendnp3-guide#14]
Hi,

I am with the following error on the install command of the maven (mvn install) 
`Running com.automatak.dnp3.impl.DNP3ManagerIntegrationTest`
`Tests run: 2, Failures: 0, Errors: 2, Skipped: 0, Time elapsed: 0.254 sec <<< FAILURE!`
`testEventOrdering(com.automatak.dnp3.impl.DNP3ManagerIntegrationTest)  Time elapsed: 0.164 sec  <<< ERROR!`
`java.lang.UnsatisfiedLinkError: /usr/lib/libopendnp3java.so: libopendnp3.so: cannot open shared object file: No such file or directory`
`	at java.lang.ClassLoader$NativeLibrary.load(Native Method)`

I have build the C project
> cmake -DDNP3_JAVA=ON -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/usr
> make
> sudo make install

The libraries are located at my system:
`sh-4.4# locate libopendnp3java.so`
`/usr/lib/libopendnp3java.so`
`sh-4.4# locate libopendnp3.so`
`/usr/lib/libopendnp3.so`

**Comment by jadamcrain** [comment]
mailing list here:

https://groups.google.com/g/automatak-dnp3
